<?php
require_once dirname(__DIR__).'/includes/config.php'; require_once dirname(__DIR__).'/includes/functions.php'; require_once dirname(__DIR__).'/includes/auth.php'; requireRole('student');
$user=currentUser()?:($_SESSION['user']??[]);$student_id=(int)($user['id']??$_SESSION['user_id']??0);
$table='results';if(!$pdo->query("SHOW TABLES LIKE 'results'")->fetch()){if($pdo->query("SHOW TABLES LIKE 'exam_attempts'")->fetch())$table='exam_attempts';elseif($pdo->query("SHOW TABLES LIKE 'exam_submissions'")->fetch())$table='exam_submissions';}
$cols=$pdo->query("SHOW COLUMNS FROM {$table}")->fetchAll(PDO::FETCH_COLUMN);$userCol=in_array('student_id',$cols)?'student_id':(in_array('user_id',$cols)?'user_id':'student_id');$dateCol=in_array('submitted_at',$cols)?'submitted_at':(in_array('created_at',$cols)?'created_at':'created_at');$statusWhere=in_array('status',$cols)?" AND a.status='completed'":"";
$q=trim($_GET['q']??'');$from=trim($_GET['from']??'');$to=trim($_GET['to']??'');$per=(int)($_GET['per_page']??10);if(!in_array($per,[10,25,50,100],true))$per=10;$page=max(1,(int)($_GET['page']??1));
$where=["a.{$userCol}=?"];$params=[$student_id];if($q!==''){$where[]="(e.title LIKE ? OR CAST(a.exam_id AS CHAR) LIKE ?)";$params[]="%$q%";$params[]="%$q%";}if($from!==''){$where[]="DATE(a.{$dateCol})>=?";$params[]=$from;}if($to!==''){$where[]="DATE(a.{$dateCol})<=?";$params[]=$to;}$whereSql=implode(' AND ',$where).$statusWhere;
$st=$pdo->prepare("SELECT COUNT(*) FROM {$table} a LEFT JOIN exams e ON e.id=a.exam_id WHERE {$whereSql}");$st->execute($params);$total=(int)$st->fetchColumn();$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$offset=($page-1)*$per;
$st=$pdo->prepare("SELECT a.*,a.{$dateCol} done_at,e.title exam_title FROM {$table} a LEFT JOIN exams e ON e.id=a.exam_id WHERE {$whereSql} ORDER BY a.{$dateCol} DESC LIMIT {$per} OFFSET {$offset}");$st->execute($params);$rows=$st->fetchAll(PDO::FETCH_ASSOC);
$page_title='Lịch sử làm bài';require_once dirname(__DIR__).'/includes/header_student.php';require_once __DIR__.'/_student_ui.php';?>
<div class="container-xl py-4"><div class="student-page-head p-4 mb-4"><h3 class="fw-bold mb-1"><i class="bi bi-clock-history me-2"></i>Lịch sử làm bài</h3><div class="text-white-50">Tra cứu kết quả và tiến độ học tập</div></div>
<form class="student-toolbar mb-4"><div class="row g-2"><div class="col-12 col-lg"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Tìm tên đề hoặc mã đề..."></div><div class="col-6 col-lg-2"><input type="date" class="form-control" name="from" value="<?=e($from)?>"></div><div class="col-6 col-lg-2"><input type="date" class="form-control" name="to" value="<?=e($to)?>"></div><div class="col-6 col-lg-2"><select class="form-select" name="per_page"><?php foreach([10,25,50,100] as $n):?><option value="<?=$n?>" <?=$per===$n?'selected':''?>><?=$n?> dòng</option><?php endforeach;?></select></div><div class="col-6 col-lg-auto"><button class="btn btn-primary w-100"><i class="bi bi-search me-1"></i>Lọc</button></div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th class="ps-4">Bài thi</th><th>Ngày làm</th><th>Điểm</th><th class="text-end pe-4">Kết quả</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="4" class="text-center text-muted py-5">Chưa có dữ liệu phù hợp.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td class="ps-4 fw-semibold"><?=e($r['exam_title']??('Bài thi #'.($r['exam_id']??'')))?></td><td><?=!empty($r['done_at'])?date('d/m/Y H:i',strtotime($r['done_at'])):'-'?></td><td><span class="badge bg-primary-subtle text-primary"><?=number_format((float)($r['score']??0),1)?> / 10</span></td><td class="text-end pe-4"><a class="btn btn-sm btn-outline-primary" href="exam_result.php?id=<?=(int)$r['id']?>"><i class="bi bi-eye me-1"></i>Xem</a></td></tr><?php endforeach;?></tbody></table></div>
<div class="d-flex flex-column flex-md-row justify-content-between align-items-center gap-2 p-3 border-top"><small class="text-muted">Hiển thị <?=$total?($offset+1):0?>–<?=min($offset+$per,$total)?> / <?=$total?></small><ul class="pagination pagination-sm mb-0"><?php for($i=max(1,$page-2);$i<=min($pages,$page+2);$i++):$qs=$_GET;$qs['page']=$i;?><li class="page-item <?=$i===$page?'active':''?>"><a class="page-link" href="?<?=http_build_query($qs)?>"><?=$i?></a></li><?php endfor;?></ul></div></div></div><?php require_once dirname(__DIR__).'/includes/footer.php';?>
