<?php
require_once dirname(__DIR__) . '/includes/config.php';
require_once dirname(__DIR__) . '/includes/functions.php';
require_once dirname(__DIR__) . '/includes/auth.php';

requireRole('student');

$subject_id = trim($_GET['subject_id'] ?? 'all');
$mode       = trim($_GET['mode'] ?? 'speed_quiz');
$limit      = (int)($_GET['limit'] ?? 20);

if ($limit < 5) $limit = 5;
if ($limit > 50) $limit = 50;

$bank = [
    'dsa' => [
        1 => ['q' => 'Độ phức tạp thời gian trung bình của QuickSort là bao nhiêu?', 'a' => 'O(n)', 'b' => 'O(n log n)', 'c' => 'O(n^2)', 'd' => 'O(log n)', 'correct' => 'B', 'exp' => 'QuickSort chia để trị có độ phức tạp trung bình O(n log n).'],
        2 => ['q' => 'Cấu trúc dữ liệu nào hoạt động theo nguyên tắc LIFO?', 'a' => 'Queue', 'b' => 'Array', 'c' => 'Stack', 'd' => 'Linked List', 'correct' => 'C', 'exp' => 'Stack hoạt động theo nguyên tắc LIFO (Last In First Out).'],
        3 => ['q' => 'Tìm kiếm nhị phân yêu cầu mảng đầu vào phải có thuộc tính gì?', 'a' => 'Kích thước < 100', 'b' => 'Đã được sắp xếp', 'c' => 'Không chứa số âm', 'd' => 'Đã đảo ngược', 'correct' => 'B', 'exp' => 'Binary Search bắt buộc mảng phải được sắp xếp trước.']
    ],
    'database' => [
        1 => ['q' => 'Mệnh đề nào trong SQL dùng để lọc dữ liệu nhóm sau GROUP BY?', 'a' => 'WHERE', 'b' => 'HAVING', 'c' => 'ORDER BY', 'd' => 'LIKE', 'correct' => 'B', 'exp' => 'HAVING dùng để lọc dữ liệu sau khi nhóm bằng GROUP BY.'],
        2 => ['q' => 'Khóa chính (Primary Key) có tính chất nào?', 'a' => 'Cho phép NULL', 'b' => 'Trùng lặp dữ liệu', 'c' => 'Duy nhất và Không NULL', 'd' => 'Có nhiều giá trị giống nhau', 'correct' => 'C', 'exp' => 'Primary Key phải là Duy nhất và Không được chứa giá trị NULL.']
    ],
    'network' => [
        1 => ['q' => 'Giao thức HTTPS hoạt động mặc định trên cổng (Port) nào?', 'a' => 'Port 80', 'b' => 'Port 21', 'c' => 'Port 443', 'd' => 'Port 8080', 'correct' => 'C', 'exp' => 'HTTPS sử dụng SSL/TLS trên cổng 443.'],
        2 => ['q' => 'Tầng nào trong mô hình OSI chịu trách nhiệm định tuyến (Routing)?', 'a' => 'Physical', 'b' => 'Data Link', 'c' => 'Network', 'd' => 'Transport', 'correct' => 'C', 'exp' => 'Network Layer (Layer 3) quản lý địa chỉ IP và thực hiện định tuyến.']
    ],
    'web' => [
        1 => ['q' => 'Phương thức HTTP nào dùng để cập nhật dữ liệu đã có?', 'a' => 'GET', 'b' => 'POST', 'c' => 'PUT / PATCH', 'd' => 'DELETE', 'correct' => 'C', 'exp' => 'PUT/PATCH dùng để cập nhật tài nguyên trong RESTful API.'],
        2 => ['q' => 'Mã HTTP Status Code 404 có nghĩa là gì?', 'a' => 'Internal Server Error', 'b' => 'Not Found', 'c' => 'Unauthorized', 'd' => 'Bad Request', 'correct' => 'B', 'exp' => '404 báo hiệu tài nguyên không tồn tại trên máy chủ.']
    ],

    // ==========================================
    // MÔN 1: KIỂM THỬ PHẦN MỀM (50 CÂU)
    // ==========================================
    'testing' => [
        1  => ['q' => 'Phương pháp kiểm thử hộp đen (Black-box Testing) dựa trên cơ sở nào?', 'a' => 'Mã nguồn chương trình', 'b' => 'Yêu cầu đặc tả chức năng', 'c' => 'Thuật toán nội bộ', 'd' => 'Sơ đồ luồng dữ liệu', 'correct' => 'B', 'exp' => 'Kiểm thử hộp đen kiểm tra chức năng dựa vào yêu cầu đặc tả mà không cần biết mã nguồn.'],
        2  => ['q' => 'Kiểm thử đơn vị (Unit Testing) thường do ai thực hiện?', 'a' => 'Khách hàng', 'b' => 'Lập trình viên (Developer)', 'c' => 'Tester độc lập', 'd' => 'Quản lý dự án (PM)', 'correct' => 'B', 'exp' => 'Unit Test do Dev viết và thực thi để kiểm tra các hàm/lớp nhỏ nhất.'],
        3  => ['q' => 'Kỹ thuật Phân vùng tương đương (Equivalence Partitioning) thuộc loại kiểm thử nào?', 'a' => 'Black-box testing', 'b' => 'White-box testing', 'c' => 'System testing', 'd' => 'Performance testing', 'correct' => 'A', 'exp' => 'Phân vùng tương đương là kỹ thuật thiết kế test case trong Kiểm thử hộp đen.'],
        4  => ['q' => 'Mục đích chính của kiểm thử hồi quy (Regression Testing) là gì?', 'a' => 'Đo tốc độ ứng dụng', 'b' => 'Đảm bảo thay đổi mới không làm hỏng tính năng cũ', 'c' => 'Kiểm tra độ bảo mật', 'd' => 'Đánh giá giao diện', 'correct' => 'B', 'exp' => 'Kiểm thử hồi quy chạy lại các test case cũ để đảm bảo code mới không làm phát sinh lỗi mới.'],
        5  => ['q' => 'Giá trị biên (Boundary Value) của tập hợp số nguyên từ 1 đến 100 bao gồm:', 'a' => '0, 1, 100, 101', 'b' => '1, 50, 100', 'c' => '-1, 0, 101, 102', 'd' => '2, 50, 99', 'correct' => 'A', 'exp' => 'Phân tích giá trị biên kiểm tra các giá trị ngay tại min, max và ngay ngoài khoảng (min-1, min, max, max+1).'],
        6  => ['q' => 'Kiểm thử hộp trắng (White-box Testing) đòi hỏi Tester phải có kỹ năng gì?', 'a' => 'Đọc và hiểu mã nguồn chương trình', 'b' => 'Hiểu về trải nghiệm UX/UI', 'c' => 'Viết tài liệu hướng dẫn sử dụng', 'd' => 'Quản lý cơ sở dữ liệu khách hàng', 'correct' => 'A', 'exp' => 'Kiểm thử hộp trắng dựa trên việc phân tích cấu trúc mã nguồn bên trong.'],
        7  => ['q' => 'Mức độ kiểm thử nào kiểm tra sự tích hợp giữa các mô-đun riêng lẻ?', 'a' => 'Unit Testing', 'b' => 'Integration Testing', 'c' => 'System Testing', 'd' => 'Acceptance Testing', 'correct' => 'B', 'exp' => 'Integration Testing kiểm tra việc giao tiếp dữ liệu giữa các module.'],
        8  => ['q' => 'Vòng đời của một lỗi (Bug Life Cycle) trạng thái bắt đầu thường là gì?', 'a' => 'Fixed', 'b' => 'Closed', 'c' => 'New / Open', 'd' => 'Reopened', 'correct' => 'C', 'exp' => 'Khi lỗi được tìm thấy và phát hiện, nó được tạo ở trạng thái New hoặc Open.'],
        9  => ['q' => 'Kiểm thử chấp nhận người dùng (UAT - User Acceptance Testing) do ai thực hiện?', 'a' => 'Developer', 'b' => 'Khách hàng / Người dùng cuối', 'c' => 'DevOps Engineer', 'd' => 'Database Administrator', 'correct' => 'B', 'exp' => 'UAT là bước kiểm thử cuối cùng do phía khách hàng thực hiện trước khi nhận bàn giao.'],
        10 => ['q' => 'Độ phủ mã (Code Coverage) là chỉ số đo lường trong loại kiểm thử nào?', 'a' => 'Black-box Testing', 'b' => 'White-box Testing', 'c' => 'Usability Testing', 'd' => 'Alpha Testing', 'correct' => 'B', 'exp' => 'Code Coverage đo lường phần trăm dòng lệnh/nhánh lệnh được thực thi bởi test suite.'],
        11 => ['q' => 'Loại kiểm thử nào đánh giá khả năng chịu tải vượt quá giới hạn thiết kế của hệ thống?', 'a' => 'Load Testing', 'b' => 'Stress Testing', 'c' => 'Usability Testing', 'd' => 'Sanity Testing', 'correct' => 'B', 'exp' => 'Stress Testing ép hệ thống hoạt động cực hạn quá tải để xem cách hệ thống xử lý khi sập.'],
        12 => ['q' => 'Khái niệm "Bug" trong kiểm thử phần mềm có nghĩa là gì?', 'a' => 'Một tính năng nâng cao', 'b' => 'Lỗi khiến phần mềm chạy sai yêu cầu', 'c' => 'Tài liệu hướng dẫn sai', 'd' => 'Tốc độ phần mềm bị chậm', 'correct' => 'B', 'exp' => 'Bug hay Defect là sự sai khác giữa kết quả thực tế (Actual Result) và kỳ vọng (Expected Result).'],
        13 => ['q' => 'Công cụ nào sau đây phổ biến nhất cho kiểm thử tự động Web (Automation Testing)?', 'a' => 'Selenium', 'b' => 'JUnit', 'c' => 'Postman', 'd' => 'JMeter', 'correct' => 'A', 'exp' => 'Selenium là framework kiểm thử tự động giao diện trình duyệt web cực kỳ phổ biến.'],
        14 => ['q' => 'Công cụ JMeter thường được sử dụng cho mục đích kiểm thử nào?', 'a' => 'Kiểm thử giao diện', 'b' => 'Kiểm thử hiệu năng / tải (Performance/Load Test)', 'c' => 'Kiểm thử bảo mật', 'd' => 'Kiểm thử Unit', 'correct' => 'B', 'exp' => 'Apache JMeter chuyên dùng để giả lập tải và đo hiệu năng API/Web.'],
        15 => ['q' => 'Ma trận truy xuất yêu cầu (RTM - Traceability Matrix) dùng để làm gì?', 'a' => 'Tính lương cho tester', 'b' => 'Đảm bảo mỗi yêu cầu chức năng đều có test case tương ứng', 'c' => 'Theo dõi thời gian chạy tự động', 'd' => 'Vẽ sơ đồ luồng dữ liệu', 'correct' => 'B', 'exp' => 'RTM giúp ánh xạ giữa Requirement và Test Case để tránh bỏ sót tính năng.'],
        16 => ['q' => 'Khái niệm "Alpha Testing" được thực hiện ở đâu?', 'a' => 'Tại môi trường khách hàng', 'b' => 'Tại nội bộ nhà phát triển phần mềm', 'c' => 'Bởi người dùng tự do trên Internet', 'd' => 'Tại phòng Lab của bên thứ ba', 'correct' => 'B', 'exp' => 'Alpha Testing được thực hiện trong nội bộ công ty phát triển trước khi đưa bản Beta cho khách hàng.'],
        17 => ['q' => 'Beta Testing xảy ra ở giai đoạn nào?', 'a' => 'Trước Alpha testing', 'b' => 'Sau Alpha testing và trước khi phát hành chính thức', 'c' => 'Trong khi viết mã nguồn', 'd' => 'Sau khi đã dừng hỗ trợ dự án', 'correct' => 'B', 'exp' => 'Beta testing phát hành bản thử nghiệm cho một nhóm người dùng cuối trải nghiệm thực tế.'],
        18 => ['q' => 'Test Case chuẩn gồm có những thành phần quan trọng nào?', 'a' => 'ID, Title, Pre-conditions, Steps, Expected Result', 'b' => 'Source code, Database link', 'c' => 'User ID, Password', 'd' => 'Server Name, IP Address', 'correct' => 'A', 'exp' => 'Một Test Case cơ bản luôn cần các bước thực hiện, tiền điều kiện và kết quả kỳ vọng.'],
        19 => ['q' => 'Kiểm thử Tĩnh (Static Testing) là hoạt động nào sau đây?', 'a' => 'Chạy mã nguồn với dữ liệu lớn', 'b' => 'Review mã nguồn, kiểm tra tài liệu thiết kế mà không chạy phần mềm', 'c' => 'Bắn dữ liệu tấn công SQL Injection', 'd' => 'Đo thời gian phản hồi API', 'correct' => 'B', 'exp' => 'Static testing kiểm tra tài liệu, code review mà không cần biên dịch hay thực thi ứng dụng.'],
        20 => ['q' => 'Kiểm thử Động (Dynamic Testing) là gì?', 'a' => 'Đọc mã nguồn trên giấy', 'b' => 'Thực thi mã nguồn với các dữ liệu đầu vào cụ thể', 'c' => 'Review tài liệu SRS', 'd' => 'Thảo luận yêu cầu với khách hàng', 'correct' => 'B', 'exp' => 'Dynamic testing yêu cầu phần mềm phải được biên dịch và chạy thực tế.'],
        21 => ['q' => 'Test Scenario khác Test Case như thế nào?', 'a' => 'Scenario là kịch bản tổng thể (Cần test cái gì), Case là chi tiết cụ thể (Test như thế nào)', 'b' => 'Scenario chi tiết hơn Test Case', 'c' => 'Test Case không có kết quả kỳ vọng', 'd' => 'Hai thuật ngữ này hoàn toàn giống nhau', 'correct' => 'A', 'exp' => 'Test Scenario định hướng phạm vi tính năng, Test Case gồm các bước chi tiết với input/output cụ thể.'],
        22 => ['q' => 'Sanity Testing là gì?', 'a' => 'Kiểm thử toàn bộ hệ thống từ đầu', 'b' => 'Kiểm thử nhanh tập trung vào chức năng vừa được sửa lỗi xem có ổn định không', 'c' => 'Kiểm thử bảo mật nâng cao', 'd' => 'Kiểm thử chịu tải tối đa', 'correct' => 'B', 'exp' => 'Sanity Testing là một tập hợp con của Regression testing, thử nhanh sau khi nhận build sửa lỗi.'],
        23 => ['q' => 'Smoke Testing có mục đích chính là gì?', 'a' => 'Đảm bảo các chức năng cơ bản nhất hoạt động ổn định trước khi nhận build kiểm thử sâu', 'b' => 'Tìm tất cả bug tiềm ẩn', 'c' => 'Đo tốc độ xử lý cơ sở dữ liệu', 'd' => 'Tự động sửa lỗi mã nguồn', 'correct' => 'A', 'exp' => 'Smoke Testing (Build Verification Test) xác nhận bản build đủ ổn định để đưa vào test chi tiết.'],
        24 => ['q' => 'Mức độ nghiêm trọng của lỗi (Severity) thể hiện điều gì?', 'a' => 'Mức độ ưu tiên sửa lỗi của lập trình viên', 'b' => 'Tác động kỹ thuật của lỗi tới hoạt động của phần mềm', 'c' => 'Độ khó khi tìm thấy lỗi', 'd' => 'Số dòng code bị ảnh hưởng', 'correct' => 'B', 'exp' => 'Severity đánh giá mức độ phá hủy/ảnh hưởng của lỗi đến hệ thống (ví dụ: Crash server = Critical).'],
        25 => ['q' => 'Mức độ ưu tiên (Priority) của lỗi thể hiện điều gì?', 'a' => 'Mức độ khẩn cấp cần sửa lỗi dựa trên góc độ kinh doanh/vận hành', 'b' => 'Tác động hệ thống', 'c' => 'Độ dài của tài liệu mô tả lỗi', 'd' => 'Tên của người phát hiện lỗi', 'correct' => 'A', 'exp' => 'Priority xác định thứ tự ưu tiên lỗi nào cần được sửa trước.'],
        26 => ['q' => 'Tình huống lỗi "High Priority - Low Severity" là trường hợp nào?', 'a' => 'Hệ thống bị sập hoàn toàn', 'b' => 'Sai logo hoặc tên công ty ở trang chủ', 'c' => 'Tính toán sai tổng tiền đơn hàng', 'd' => 'Rò rỉ dữ liệu mật', 'correct' => 'B', 'exp' => 'Sai logo trang chủ không gây sập hệ thống (Low Severity) nhưng ảnh hưởng thương hiệu cần sửa gấp (High Priority).'],
        27 => ['q' => 'Tình huống lỗi "High Severity - Low Priority" là trường hợp nào?', 'a' => 'Nút Đăng nhập không hoạt động', 'b' => 'Tính năng sập ứng dụng ở một hệ điều hành rất cũ hiếm người dùng', 'c' => 'Đổi màu nút bấm sai quy chuẩn', 'd' => 'Lỗi chính tả trong thông báo', 'correct' => 'B', 'exp' => 'Lỗi gây sập app (High Severity) nhưng ở môi trường/hệ điều hành cực hiếm người dùng nên chưa gấp (Low Priority).'],
        28 => ['q' => 'Bảng quyết định (Decision Table) cực kỳ hữu ích khi thiết kế test case cho trường hợp nào?', 'a' => 'Hệ thống có nhiều kết hợp điều kiện đầu vào phức tạp', 'b' => 'Chỉ có 1 trường nhập dữ liệu', 'c' => 'Đo hiệu năng hệ thống', 'd' => 'So sánh màu sắc giao diện', 'correct' => 'A', 'exp' => 'Decision Table giúp liệt kê đầy đủ các tổ hợp quy tắc nghiệp vụ logic phức tạp.'],
        29 => ['q' => 'Sơ đồ chuyển trạng thái (State Transition Testing) áp dụng tốt nhất cho:', 'a' => 'Hệ thống chuyển đổi qua các trạng thái khác nhau dựa vào sự kiện (như Đơn hàng: Mới -> Đã thanh toán -> Đã giao)', 'b' => 'Trang web tĩnh đọc tin tức', 'c' => 'Tính toán cộng trừ số học', 'd' => 'So khớp chuỗi ký tự', 'correct' => 'A', 'exp' => 'State Transition Testing theo dõi sự thay đổi trạng thái của đối tượng khi nhận các sự kiện tác động.'],
        30 => ['q' => 'Bảng câu hỏi kiểm thử khả năng sử dụng (Usability Testing) hướng tới yếu tố nào?', 'a' => 'Sự thân thiện, dễ truy cập và dễ dùng của giao diện', 'b' => 'Tốc độ phản hồi SQL query', 'c' => 'Độ phủ dòng code', 'd' => 'Khả năng mã hóa dữ liệu', 'correct' => 'A', 'exp' => 'Usability Testing đánh giá trải nghiệm người dùng (UX/UI).'],
        31 => ['q' => 'Postman là công cụ chuyên dùng để kiểm thử loại đối tượng nào?', 'a' => 'API / Web Services', 'b' => 'Mobile App UI', 'c' => 'Mã nguồn C++', 'd' => 'File PDF', 'correct' => 'A', 'exp' => 'Postman giúp gửi các request HTTP (GET, POST, PUT, DELETE) để test API.'],
        32 => ['q' => 'Kiểm thử Monkey Testing là phương pháp gì?', 'a' => 'Nhập dữ liệu ngẫu nhiên, bất kỳ để cố gắng làm sập hệ thống', 'b' => 'Viết kịch bản tự động theo quy chuẩn', 'c' => 'Kiểm thử theo tài liệu thiết kế tỉ mỉ', 'd' => 'Đo tốc độ tải trang', 'correct' => 'A', 'exp' => 'Monkey Testing nhập liệu ngẫu nhiên không cần kịch bản để xem hệ thống có bị crash bất ngờ hay không.'],
        33 => ['q' => 'Exploratory Testing (Kiểm thử khám phá) là gì?', 'a' => 'Vừa học, vừa thiết kế và thực thi test case cùng lúc mà không cần kịch bản trước', 'b' => 'Chạy kịch bản tự động có sẵn', 'c' => 'Đọc tài liệu mã nguồn', 'd' => 'Kiểm thử dựa theo RTM', 'correct' => 'A', 'exp' => 'Exploratory testing dựa trên kinh nghiệm và sự suy luận tức thời của tester.'],
        34 => ['q' => 'Tài liệu SRS (Software Requirement Specification) chứa đựng điều gì?', 'a' => 'Đặc tả yêu cầu phần mềm', 'b' => 'Mã nguồn của hệ thống', 'c' => 'Danh sách bug đã phát hiện', 'd' => 'Lịch làm việc của lập trình viên', 'correct' => 'A', 'exp' => 'SRS là tài liệu mô tả chi tiết các chức năng và yêu cầu hệ thống phải đạt được.'],
        35 => ['q' => 'Trong quy trình V-Model, giai đoạn Unit Test song song tương ứng với giai đoạn nào?', 'a' => 'Detailed Design (Thiết kế chi tiết)', 'b' => 'Requirements Analysis', 'c' => 'System Design', 'd' => 'Maintenance', 'correct' => 'A', 'exp' => 'Trong V-Model, Unit Test được chuẩn bị và đối ứng trực tiếp với Thiết kế chi tiết.'],
        36 => ['q' => 'Trong V-Model, Acceptance Test tương ứng đối ứng với bước nào?', 'a' => 'Requirements Analysis (Phân tích yêu cầu)', 'b' => 'Coding', 'c' => 'Module Design', 'd' => 'Architecture Design', 'correct' => 'A', 'exp' => 'Acceptance Test dùng để nghiệm thu xem sản phẩm có đáp ứng đúng Requirements ban đầu không.'],
        37 => ['q' => 'Đâu là công cụ quản lý Bug/Task phổ biến hàng đầu hiện nay?', 'a' => 'Jira', 'b' => 'Photoshop', 'c' => 'Visual Studio Code', 'd' => 'Wireshark', 'correct' => 'A', 'exp' => 'Jira (Atlassian) là công cụ quản lý dự án và bug phổ biến bậc nhất trong các công ty Agile.'],
        38 => ['q' => 'Kỹ thuật Phân tích giá trị biên chọn các giá trị nào sau đây cho miền [10, 50]?', 'a' => '9, 10, 50, 51', 'b' => '10, 20, 30, 40', 'c' => '0, 10, 50, 100', 'd' => '11, 25, 49', 'correct' => 'A', 'exp' => 'Giá trị biên lấy ngay tại biên (10, 50) và 2 điểm sát cạnh ngoài biên (9, 51).'],
        39 => ['q' => 'Nguyên lý kiểm thử: "Kiểm thử chứng minh sự có mặt của lỗi" có nghĩa là:', 'a' => 'Kiểm thử chỉ ra lỗi đang tồn tại chứ không thể chứng minh phần mềm 100% không có lỗi', 'b' => 'Phần mềm không thể có lỗi', 'c' => 'Càng test càng hết sạch bug', 'd' => 'Chỉ cần test 1 lần là đủ', 'correct' => 'A', 'exp' => 'Một trong 7 nguyên lý kiểm thử: Testing can show that defects are present, but cannot prove that there are no defects.'],
        40 => ['q' => 'Hiện tượng "Pesticide Paradox" (Nghịch lý thuốc trừ sâu) trong testing nghĩa là gì?', 'a' => 'Nếu lặp đi lặp lại một tập test case cũ thì nó sẽ không còn tìm thêm được lỗi mới', 'b' => 'Máy tính bị nhiễm virus', 'c' => 'Code càng viết càng chậm', 'd' => 'Tester bị kiệt sức', 'correct' => 'A', 'exp' => 'Cần phải cập nhật test case thường xuyên vì bug cũ đã bị phát hiện và sửa hết.'],
        41 => ['q' => 'Mục đích của Mutation Testing là gì?', 'a' => 'Đánh giá chất lượng của chính bộ Test Case bằng cách cố tình tạo lỗi nhỏ trong code', 'b' => 'Đo tốc độ internet', 'c' => 'Thay đổi giao diện tự động', 'd' => 'Mã hóa mật khẩu', 'correct' => 'A', 'exp' => 'Mutation testing sửa nhẹ code (tạo đột biến) để xem test case có phát hiện ra lỗi đó không.'],
        42 => ['q' => 'Kiểm thử hiệu năng bao gồm các loại nào?', 'a' => 'Load, Stress, Endurance, Spike Testing', 'b' => 'Unit, Integration, System Test', 'c' => 'Black-box, White-box Test', 'd' => 'Alpha, Beta Test', 'correct' => 'A', 'exp' => 'Performance testing tổng hợp kiểm thử tải, chịu tải cực hạn, tải kéo dài và tải đột biến.'],
        43 => ['q' => 'Kiểm thử an ninh bảo mật (Security Testing) nhằm mục đích gì?', 'a' => 'Phát hiện lỗ hổng có thể bị khai thác tấn công dữ liệu', 'b' => 'Đo thời gian phản hồi trang', 'c' => 'Kiểm tra màu sắc giao diện', 'd' => 'Đếm số lượng truy cập', 'correct' => 'A', 'exp' => 'Security Testing phát hiện các lỗ hổng như SQLi, XSS, CSRF...'],
        44 => ['q' => 'Đâu là một framework Unit Test dành cho ngôn ngữ Java?', 'a' => 'JUnit', 'b' => 'PyTest', 'c' => 'NUnit', 'd' => 'Jest', 'correct' => 'A', 'exp' => 'JUnit là thư viện Unit Test tiêu chuẩn cho ứng dụng Java.'],
        45 => ['q' => 'Công cụ Cypress / Playwright dùng để kiểm thử loại ứng dụng nào?', 'a' => 'End-to-End Web Applications', 'b' => 'Cơ sở dữ liệu Oracle', 'c' => 'Mạng viễn thông 5G', 'd' => 'File hệ điều hành Windows', 'correct' => 'A', 'exp' => 'Cypress và Playwright là các công cụ E2E test hiện đại cho Web.'],
        46 => ['q' => 'Khái niệm "Stub" và "Mock" thường được sử dụng trong mức kiểm thử nào?', 'a' => 'Unit & Integration Testing', 'b' => 'UAT Testing', 'c' => 'Stress Testing', 'd' => 'Beta Testing', 'correct' => 'A', 'exp' => 'Stub và Mock giả lập các phụ thuộc (dependency) để kiểm thử mô-đun độc lập.'],
        47 => ['q' => 'Giai đoạn Test Closure trong quy trình kiểm thử bao gồm việc gì?', 'a' => 'Tổng kết, đánh giá báo cáo hoàn thành kiểm thử và lưu trữ tài liệu', 'b' => 'Bắt đầu viết mã nguồn', 'c' => 'Tạo bug mới', 'd' => 'Cài đặt hệ điều hành', 'correct' => 'A', 'exp' => 'Test Closure thu thập dữ liệu tổng kết từ chu kỳ kiểm thử đã hoàn thành.'],
        48 => ['q' => 'Shift-Left Testing nghĩa là gì trong quy trình phát triển Aglie/DevOps?', 'a' => 'Đưa hoạt động kiểm thử vào càng sớm càng tốt ngay từ đầu dự án', 'b' => 'Dời kiểm thử sang cuối dự án', 'c' => 'Không cần thực hiện kiểm thử', 'd' => 'Chỉ cho khách hàng kiểm thử', 'correct' => 'A', 'exp' => 'Shift-Left chuyển hoạt động test sang bên trái quy trình (thực hiện sớm từ khâu thiết kế/yêu cầu).'],
        49 => ['q' => 'Báo cáo lỗi (Defect Report) chuẩn KHÔNG nhất thiết phải có thông tin nào?', 'a' => 'Mã số định danh lỗi (Bug ID)', 'b' => 'Các bước tái hiện lỗi (Steps to Reproduce)', 'c' => 'Mức lương của lập trình viên viết đoạn code đó', 'd' => 'Kết quả thực tế và kết quả mong đợi', 'correct' => 'C', 'exp' => 'Mức lương cá nhân không liên quan tới báo cáo kỹ thuật kỹ năng kiểm thử.'],
        50 => ['q' => 'Tiêu chí thoát (Exit Criteria) của kiểm thử quy định điều gì?', 'a' => 'Các điều kiện bắt buộc phải đạt để chính thức kết thúc giai đoạn kiểm thử', 'b' => 'Lịch xin nghỉ phép của Tester', 'c' => 'Thời điểm bật máy máy chủ', 'd' => 'Số lượng máy tính trong phòng test', 'correct' => 'A', 'exp' => 'Exit Criteria xác định khi nào thì kiểm thử đủ điều kiện để dừng lại (ví dụ 100% test case đã chạy, 0 lỗi critical).']
    ],

    // ==========================================
    // MÔN 2: LẬP TRÌNH JAVA (50 CÂU)
    // ==========================================
    'java' => [
        1  => ['q' => 'Từ khóa nào trong Java được sử dụng để khai báo một Hằng số?', 'a' => 'const', 'b' => 'static', 'c' => 'final', 'd' => 'immutable', 'correct' => 'C', 'exp' => 'Từ khóa final dùng để biến một biến thành hằng số không thể gán lại giá trị.'],
        2  => ['q' => 'Phương thức nào là điểm bắt đầu (entry point) của chương trình Java Console?', 'a' => 'public void start()', 'b' => 'public static void main(String[] args)', 'c' => 'public void main()', 'd' => 'static void run()', 'correct' => 'B', 'exp' => 'Cú pháp chính xác của phương thức chạy Java là public static void main(String[] args).'],
        3  => ['q' => 'Tính chất nào giúp Java có thể "Write Once, Run Anywhere"?', 'a' => 'Biên dịch ra Bytecode và chạy trên JVM', 'b' => 'Dùng trình biên dịch C++', 'c' => 'Chạy trực tiếp trên phần cứng', 'd' => 'Không cần bộ nhớ RAM', 'correct' => 'A', 'exp' => 'Mã Java dịch ra Bytecode (.class) và được thực thi bởi máy ảo Java (JVM) trên từng HĐH.'],
        4  => ['q' => 'Tập hợp (Collection) nào trong Java KHÔNG cho phép lưu trữ phần tử trùng lặp?', 'a' => 'ArrayList', 'b' => 'LinkedList', 'c' => 'Set (HashSet)', 'd' => 'Vector', 'correct' => 'C', 'exp' => 'Giao diện Set bảo đảm các phần tử lưu trữ là duy nhất.'],
        5  => ['q' => 'Kích thước của kiểu dữ liệu `int` trong Java là bao nhiêu bit?', 'a' => '8-bit', 'b' => '16-bit', 'c' => '32-bit', 'd' => '64-bit', 'correct' => 'C', 'exp' => 'Trong Java, kiểu int có kích thước cố định là 32-bit (4 bytes).'],
        6  => ['q' => 'Giá trị mặc định của một biến kiểu `boolean` trong thuộc tính lớp Java là gì?', 'a' => 'true', 'b' => 'false', 'c' => 'null', 'd' => '0', 'correct' => 'B', 'exp' => 'Biến boolean thuộc tính lớp mặc định nhận giá trị false.'],
        7  => ['q' => 'Khái niệm "Garbage Collection" (Bộ gom rác) trong Java có nhiệm vụ gì?', 'a' => 'Sắp xếp lại mã nguồn', 'b' => 'Tự động giải phóng bộ nhớ Heap của các đối tượng không còn được tham chiếu', 'c' => 'Xóa file .class hỏng', 'd' => 'Tắt ứng dụng khi bị sập', 'correct' => 'B', 'exp' => 'Garbage Collector tự động giải phóng RAM giúp quản lý bộ nhớ an toàn.'],
        8  => ['q' => 'Trong Java, lớp nào là lớp cha cao nhất của TẤT CẢ các lớp?', 'a' => 'java.lang.Class', 'b' => 'java.lang.Object', 'c' => 'java.lang.System', 'd' => 'java.util.Super', 'correct' => 'B', 'exp' => 'Mọi lớp trong Java đều mặc định kế thừa trực tiếp hoặc gián tiếp từ java.lang.Object.'],
        9  => ['q' => 'Từ khóa nào dùng để bắt ngoại lệ trong Java?', 'a' => 'try - catch', 'b' => 'if - else', 'c' => 'do - while', 'd' => 'throw - return', 'correct' => 'A', 'exp' => 'Khối try-catch dùng để xử lý exception khi chương trình chạy.'],
        10 => ['q' => 'Điểm khác biệt chính giữa `String`, `StringBuilder` và `StringBuffer` là gì?', 'a' => 'String là immutable (bất biến), StringBuilder nhanh nhưng không thread-safe, StringBuffer thread-safe', 'b' => 'String thay đổi được độ dài', 'c' => 'StringBuilder chậm hơn String', 'd' => 'StringBuffer không lưu ký tự', 'correct' => 'A', 'exp' => 'String bất biến; StringBuilder tối ưu tốc độ đơn luồng; StringBuffer an toàn trong đa luồng.'],
        11 => ['q' => 'Từ khóa `static` gắn trước một phương thức có ý nghĩa gì?', 'a' => 'Phương thức thuộc về Lớp chứ không thuộc về đối tượng cụ thể (gọi không cần new)', 'b' => 'Phương thức không thể thay đổi', 'c' => 'Phương thức bị ẩn đi', 'd' => 'Phương thức chạy chậm hơn', 'correct' => 'A', 'exp' => 'Thành phần static có thể được gọi trực tiếp thông qua tên Lớp (ClassName.method()).'],
        12 => ['q' => 'Đâu là một Wrapper class tương ứng cho kiểu dữ liệu nguyên thủy `char`?', 'a' => 'Char', 'b' => 'Character', 'c' => 'String', 'd' => 'Text', 'correct' => 'B', 'exp' => 'Character là Wrapper class đại diện cho char.'],
        13 => ['q' => 'Hiện tượng Autoboxing trong Java là gì?', 'a' => 'Tự động chuyển đổi từ kiểu dữ liệu nguyên thủy sang Wrapper class tương ứng', 'b' => 'Tự động nén file .java thành .zip', 'c' => 'Tự động tạo giao diện', 'd' => 'Tự động sửa lỗi cú pháp', 'correct' => 'A', 'exp' => 'Ví dụ: tự động chuyển kiểu `int` thành đối tượng `Integer`.'],
        14 => ['q' => 'Ngoại lệ `NullPointerException` xảy ra khi nào?', 'a' => 'Chia một số cho 0', 'b' => 'Thao tác truy cập phương thức/thuộc tính trên một biến tham chiếu đang trỏ tới `null`', 'c' => 'Ép sai kiểu dữ liệu', 'd' => 'Vượt quá chỉ số mảng', 'correct' => 'B', 'exp' => 'Khi biến đối tượng chưa được khởi tạo (bằng null) mà gọi hàm thì sẽ ném NullPointerException.'],
        15 => ['q' => 'Interface trong Java 8 trở đi có thể chứa nội dung hàm nếu dùng từ khóa nào?', 'a' => 'abstract', 'b' => 'default / static', 'c' => 'public only', 'd' => 'private only', 'correct' => 'B', 'exp' => 'Từ Java 8, Interface cho phép khai báo phương thức có thân hàm với từ khóa default hoặc static.'],
        16 => ['q' => 'Khối lệnh `finally` trong cấu trúc try-catch-finally có đặc điểm gì?', 'a' => 'Luôn luôn được thực thi dù có ngoại lệ xảy ra hay không', 'b' => 'Chỉ thực thi khi có lỗi', 'c' => 'Chỉ thực thi khi KHÔNG có lỗi', 'd' => 'Bị bỏ qua nếu có return', 'correct' => 'A', 'exp' => 'Khối finally luôn chạy để đóng tài nguyên (file, connection...) trừ khi JVM bị shutdown đột ngột.'],
        17 => ['q' => 'Mảng trong Java được khởi tạo nằm ở vùng nhớ nào?', 'a' => 'Stack Memory', 'b' => 'Heap Memory', 'c' => 'Register', 'd' => 'ROM', 'correct' => 'B', 'exp' => 'Mọi mảng và đối tượng trong Java đều được cấp phát không gian trên bộ nhớ Heap.'],
        18 => ['q' => 'Từ khóa `transient` dùng trước thuộc tính của lớp có ý nghĩa gì?', 'a' => 'Không tham gia vào quá trình Tuần tự hóa (Serialization)', 'b' => 'Biến đó không thể thay đổi giá trị', 'c' => 'Biến đó biến thành chuỗi', 'd' => 'Biến đó có thể dùng ở lớp khác', 'correct' => 'A', 'exp' => 'Transient báo cho JVM biết bỏ qua thuộc tính này khi Serialize đối tượng ra file/network.'],
        19 => ['q' => 'Thư viện Java Stream API được giới thiệu chính thức ở phiên bản Java nào?', 'a' => 'Java 5', 'b' => 'Java 6', 'c' => 'Java 8', 'd' => 'Java 11', 'correct' => 'C', 'exp' => 'Stream API và Lambda Expression là đột phá lớn ra đời từ Java 8.'],
        20 => ['q' => 'Cú pháp Lambda Expression nào sau đây đúng trong Java?', 'a' => '(a, b) -> a + b', 'b' => 'function(a, b) { return a + b; }', 'c' => 'def (a, b): a + b', 'd' => 'val a, b => a + b', 'correct' => 'A', 'exp' => 'Cú pháp Lambda Java 8 có dạng `(parameters) -> expression`.'],
        21 => ['q' => 'Giao diện `Comparable` cung cấp phương thức nào để sắp xếp?', 'a' => 'compareTo(Object o)', 'b' => 'compare(Object o1, Object o2)', 'c' => 'sort()', 'd' => 'equals()', 'correct' => 'A', 'exp' => 'Comparable chứa hàm compareTo() để định nghĩa thứ tự sắp xếp tự nhiên.'],
        22 => ['q' => 'Giao diện `Comparator` chứa phương thức chính nào để so sánh 2 đối tượng?', 'a' => 'compare(T o1, T o2)', 'b' => 'compareTo(T o)', 'c' => 'equals(T o)', 'd' => 'sort(T o1, T o2)', 'correct' => 'A', 'exp' => 'Comparator dùng phương thức compare(o1, o2) để tạo bộ so sánh tùy biến bên ngoài.'],
        23 => ['q' => 'Lớp `HashMap` lưu trữ dữ liệu dưới dạng nào?', 'a' => 'Danh sách chỉ số', 'b' => 'Cặp Key - Value (Khóa - Giá trị)', 'c' => 'Cây nhị phân thuần', 'd' => 'Mảng 2 chiều', 'correct' => 'B', 'exp' => 'HashMap lưu cặp Key-Value, Key là duy nhất.'],
        24 => ['q' => 'Điểm khác biệt giữa `HashMap` và `Hashtable` là gì?', 'a' => 'HashMap cho phép 1 Key null và không thread-safe; Hashtable không cho null và thread-safe', 'b' => 'Hashtable nhanh hơn HashMap', 'c' => 'HashMap không lưu được chuỗi', 'd' => 'Giống hệt nhau không khác gì', 'correct' => 'A', 'exp' => 'Hashtable là class cũ đồng bộ (synchronized), HashMap hiện đại hơn và không đồng bộ.'],
        25 => ['q' => 'Từ khóa `synchronized` trong Java đa luồng có mục đích gì?', 'a' => 'Tăng tốc độ chạy của luồng', 'b' => 'Khóa tài nguyên, đảm bảo tại một thời điểm chỉ 1 luồng được truy cập', 'c' => 'Tự động tạo thêm luồng mới', 'd' => 'Tạm dừng luồng vĩnh viễn', 'correct' => 'B', 'exp' => 'Synchronized ngăn ngừa xung đột dữ liệu (Race condition) trong đa luồng.'],
        26 => ['q' => 'Phương thức `Thread.sleep(1000)` làm gì?', 'a' => 'Dừng luồng hiện tại trong 1000 miligiây (1 giây)', 'b' => 'Xóa luồng sau 1 giây', 'c' => 'Tạo luồng mới sau 1 giây', 'd' => 'Chạy luồng nhanh gấp 1000 lần', 'correct' => 'A', 'exp' => 'sleep() tạm dừng luồng theo số miligiây được truyền vào.'],
        27 => ['q' => 'Lớp `Optional` trong Java 8 dùng để làm gì?', 'a' => 'Tránh lỗi NullPointerException bằng cách bọc giá trị có thể null', 'b' => 'Tạo mảng động', 'c' => 'Tăng tốc thuật toán', 'd' => 'Đọc ghi file nhanh hơn', 'correct' => 'A', 'exp' => 'Optional giúp kiểm tra sự tồn tại của dữ liệu rõ ràng hơn thay vì check `if (x == null)`.'],
        28 => ['q' => 'Từ khóa `package` trong Java dùng để làm gì?', 'a' => 'Gói các lớp liên quan lại với nhau để quản lý không gian tên (namespace)', 'b' => 'Nén code lại', 'c' => 'Khởi tạo ứng dụng', 'd' => 'Tạo file cài đặt .exe', 'correct' => 'A', 'exp' => 'Package nhóm các class liên quan lại tránh trùng tên và dễ quản lý.'],
        29 => ['q' => 'Trong Java, từ khóa `import` dùng để:', 'a' => 'Sử dụng các lớp từ package khác trong file hiện tại', 'b' => 'Tải dữ liệu từ cơ sở dữ liệu', 'c' => 'Xuất dữ liệu ra màn hình', 'd' => 'Xóa bỏ một lớp', 'correct' => 'A', 'exp' => 'import khai báo tham chiếu tới các lớp thuộc package khác.'],
        30 => ['q' => 'Phương thức `equals()` mặc định của lớp `Object` so sánh điều gì?', 'a' => 'So sánh địa chỉ ô nhớ (tham chiếu `==`) của 2 đối tượng', 'b' => 'So sánh độ dài nội dung', 'c' => 'So sánh tên biến', 'd' => 'So sánh thời điểm khởi tạo', 'correct' => 'A', 'exp' => 'Mặc định Object.equals() so sánh tham chiếu. Các lớp như String, Integer override lại để so sánh giá trị.'],
        31 => ['q' => 'Vùng nhớ Stack trong Java dùng để lưu trữ gì?', 'a' => 'Biến cục bộ và các lời gọi phương thức (call frames)', 'b' => 'Tất cả các đối tượng new', 'c' => 'Hình ảnh và video', 'd' => 'Lưu file dữ liệu tĩnh', 'correct' => 'A', 'exp' => 'Stack chứa khung lời gọi hàm và các biến nguyên thủy/tham chiếu cục bộ trong hàm.'],
        32 => ['q' => 'Khái niệm "Method Reference" trong Java 8 có cú pháp biểu diễn như thế nào?', 'a' => 'System.out::println', 'b' => 'System.out->println', 'c' => 'System.out.println()', 'd' => 'System.out#println', 'correct' => 'A', 'exp' => 'Method reference dùng toán tử hai dấu hai chấm `Class::method`.'],
        33 => ['q' => 'Lớp `java.io.Serializable` là loại interface gì?', 'a' => 'Marker Interface (Giao diện đánh dấu, không có phương thức nào)', 'b' => 'Functional Interface', 'c' => 'Abstract Interface', 'd' => 'Default Interface', 'correct' => 'A', 'exp' => 'Serializable là Marker Interface rỗng, chỉ dùng để đánh dấu lớp cho phép serialization.'],
        34 => ['q' => 'Kiểu dữ liệu `float` trong Java phải ghi kèm hậu tố nào khi gán giá trị số thực?', 'a' => 'f hoặc F (ví dụ: 3.14f)', 'b' => 'd hoặc D', 'c' => 'l hoặc L', 'd' => 'm hoặc M', 'correct' => 'A', 'exp' => 'Số thực mặc định trong Java là `double`, nên `float` bắt buộc có hậu tố `f`.'],
        35 => ['q' => 'Toán tử `instanceof` dùng để làm gì?', 'a' => 'Kiểm tra một đối tượng có phải là thể hiện của một Lớp/Interface cụ thể hay không', 'b' => 'Tạo bản sao đối tượng', 'c' => 'Tính kích thước dung lượng đối tượng', 'd' => 'Xóa đối tượng', 'correct' => 'A', 'exp' => 'instanceof trả về boolean kiểm tra kiểu thực tế của đối tượng.'],
        36 => ['q' => 'Điều gì xảy ra khi bạn cố tình gọi `System.gc()`?', 'a' => 'Yêu cầu (gợi ý) JVM chạy Garbage Collector, nhưng không đảm bảo nó chạy ngay lập tức', 'b' => 'JVM bị sập ngay lập tức', 'c' => 'Xóa toàn bộ RAM máy tính', 'd' => 'Không có tác dụng gì cả', 'correct' => 'A', 'exp' => 'System.gc() chỉ mang tính chất đề xuất gợi ý với JVM.'],
        37 => ['q' => 'Cấu trúc dữ liệu nào trong Java implemented theo mô hình LIFO?', 'a' => 'java.util.Stack / ArrayDeque', 'b' => 'LinkedList Queue', 'c' => 'TreeSet', 'd' => 'PriorityQueue', 'correct' => 'A', 'exp' => 'Stack và ArrayDeque (dùng làm stack) tuân theo LIFO.'],
        38 => ['q' => 'Lớp `ArrayList` thay đổi kích thước mảng như thế nào khi bị đầy?', 'a' => 'Tự động cấp phát mảng mới lớn hơn (thường tăng khoảng 50% dung lượng) và copy dữ liệu sang', 'b' => 'Tăng gấp 10 lần', 'c' => 'Không thể tăng thêm', 'd' => 'Tạo file lưu xuống ổ cứng', 'correct' => 'A', 'exp' => 'ArrayList tự tăng dung lượng nội bộ (growth factor ~ 1.5) khi vượt quá capacity.'],
        39 => ['q' => 'Interface nào là root interface của Java Collection Framework (ngoại trừ Map)?', 'a' => 'java.util.Collection', 'b' => 'java.util.List', 'c' => 'java.util.Iterable', 'd' => 'java.util.Set', 'correct' => 'A', 'exp' => 'Collection là interface gốc cho List, Set, Queue (Iterable là cha của Collection).'],
        40 => ['q' => 'Enum trong Java có thể chứa các thành phần nào?', 'a' => 'Hằng số, Thuộc tính, Phương thức và Constructor', 'b' => 'Chỉ hằng số nguyên', 'c' => 'Không thể chứa phương thức', 'd' => 'Chỉ là chuỗi văn bản', 'correct' => 'A', 'exp' => 'Enum trong Java rất mạnh mẽ, là một loại Lớp đặc biệt có đầy đủ phương thức và thuộc tính.'],
        41 => ['q' => 'Để chạy chương trình Java từ dòng lệnh terminal, lệnh nào dùng để biên dịch file `.java`?', 'a' => 'javac FileName.java', 'b' => 'java FileName.java', 'c' => 'run FileName.java', 'd' => 'compile FileName.java', 'correct' => 'A', 'exp' => '`javac` là trình biên dịch mã nguồn Java ra mã máy Bytecode.'],
        42 => ['q' => 'Lệnh nào dùng để thực thi file Java đã biên dịch (`FileName.class`) từ terminal?', 'a' => 'java FileName', 'b' => 'javac FileName', 'c' => 'execute FileName', 'd' => 'start FileName', 'correct' => 'A', 'exp' => 'Dùng lệnh `java + TênClass` để máy ảo JVM chạy chương trình.'],
        43 => ['q' => 'Ngoại lệ `Checked Exception` trong Java có đặc điểm gì?', 'a' => 'Bắt buộc phải được xử lý (try-catch) hoặc khai báo (throws) ngay tại thời điểm biên dịch', 'b' => 'Chỉ xuất hiện khi chạy runtime', 'c' => 'Là lỗi phần cứng', 'd' => 'Không thể bắt được', 'correct' => 'A', 'exp' => 'Checked Exception (như IOException, SQLException) được kiểm tra ngay lúc biên dịch code.'],
        44 => ['q' => 'Ngoại lệ `Unchecked Exception` là gì?', 'a' => 'Các ngoại lệ kế thừa từ RuntimeException, không bắt buộc khai báo lúc biên dịch', 'b' => 'Lỗi cú pháp', 'c' => 'Lỗi không chạy được code', 'd' => 'Chỉ có trong C++', 'correct' => 'A', 'exp' => 'Unchecked Exception (như NullPointerException, ArrayIndexOutOfBoundsException) xảy ra lúc runtime.'],
        45 => ['q' => 'Lớp `Varargs` (Variable Arguments) trong Java được khai báo bằng ký hiệu nào?', 'a' => 'DataType... variableName', 'b' => 'DataType[]... variableName', 'c' => 'DataType* variableName', 'd' => 'DataType& variableName', 'correct' => 'A', 'exp' => 'Dấu 3 chấm `...` cho phép truyền số lượng tham số tùy ý vào hàm.'],
        46 => ['q' => 'Kết quả của biểu thức `10 + 20 + "Java"` trong Java là gì?', 'a' => '"30Java"', 'b' => '"1020Java"', 'c' => 'Lỗi biên dịch', 'd' => '"Java30"', 'correct' => 'A', 'exp' => 'Thực hiện từ trái qua phải: 10 + 20 = 30; 30 + "Java" = "30Java".'],
        47 => ['q' => 'Kết quả của biểu thức `"Java" + 10 + 20` trong Java là gì?', 'a' => '"Java1020"', 'b' => '"Java30"', 'c' => '"30Java"', 'd' => 'Lỗi runtime', 'correct' => 'A', 'exp' => 'Thực hiện từ trái qua phải: "Java" + 10 = "Java10"; "Java10" + 20 = "Java1020".'],
        48 => ['q' => 'Phương thức `hashCode()` của Object trả về kiểu dữ liệu gì?', 'a' => 'int', 'b' => 'long', 'c' => 'String', 'd' => 'boolean', 'correct' => 'A', 'exp' => 'hashCode() trả về số nguyên int đại diện cho mã băm của đối tượng.'],
        49 => ['q' => 'Nhiều Thread cùng truy cập vào một tài nguyên mà không đồng bộ dẫn đến hiện tượng gì?', 'a' => 'Race Condition (Tình trạng tranh chấp dữ liệu)', 'b' => 'Memory Leak', 'c' => 'Stack Overflow', 'd' => 'Deadlock tự động gỡ', 'correct' => 'A', 'exp' => 'Race Condition xảy ra khi nhiều luồng cùng đọc/ghi tài nguyên dùng chung gây hỏng dữ liệu.'],
        50 => ['q' => 'Công cụ Build tool phổ biến cho quản lý thư viện dự án Java hiện nay là gì?', 'a' => 'Maven / Gradle', 'b' => 'Npm / Yarn', 'c' => 'Pip', 'd' => 'Composer', 'correct' => 'A', 'exp' => 'Maven và Gradle là 2 build tool tiêu chuẩn của hệ sinh thái Java.']
    ],

    // ==========================================
    // MÔN 3: LẬP TRÌNH HƯỚNG ĐỐI TƯỢNG - OOP (50 CÂU)
    // ==========================================
    'oop' => [
        1  => ['q' => 'Tính chất nào của OOP giúp che giấu chi tiết cài đặt bên trong và bảo vệ dữ liệu?', 'a' => 'Đóng gói (Encapsulation)', 'b' => 'Kế thừa (Inheritance)', 'c' => 'Đa hình (Polymorphism)', 'd' => 'Trừu tượng (Abstraction)', 'correct' => 'A', 'exp' => 'Đóng gói gom thuộc tính và phương thức vào lớp, dùng access modifier để giới hạn quyền truy cập.'],
        2  => ['q' => 'Nạp chồng phương thức (Method Overloading) thể hiện tính đa hình ở thời điểm nào?', 'a' => 'Compile-time (Lúc biên dịch)', 'b' => 'Runtime (Lúc chạy)', 'c' => 'Link-time', 'd' => 'Load-time', 'correct' => 'A', 'exp' => 'Overloading xác định hàm nào được gọi dựa trên tham số ngay từ thời điểm biên dịch.'],
        3  => ['q' => 'Từ khóa `super` dùng để làm gì trong lập trình hướng đối tượng?', 'a' => 'Truy cập đến thuộc tính, phương thức hoặc constructor của lớp cha', 'b' => 'Tạo đối tượng lớp con', 'c' => 'Xóa đối tượng cha', 'd' => 'Khóa phương thức không cho sửa', 'correct' => 'A', 'exp' => '`super` đại diện cho thể hiện của lớp cha trực tiếp.'],
        4  => ['q' => 'Lớp trừu tượng (Abstract Class) khác với Interface ở điểm quan trọng nào?', 'a' => 'Abstract Class có thể chứa các phương thức đã triển khai mã nguồn (Concrete Method)', 'b' => 'Interface cho phép tạo đối tượng new', 'c' => 'Interface chứa biến thường có thể sửa giá trị', 'd' => 'Abstract Class không thể có constructor', 'correct' => 'A', 'exp' => 'Abstract class hỗ trợ cả hàm trừu tượng lẫn hàm có code xử lý cụ thể.'],
        5  => ['q' => 'Bốn trụ cột chính của Lập trình Hướng đối tượng (OOP) bao gồm:', 'a' => 'Encapsulation, Inheritance, Polymorphism, Abstraction', 'b' => 'Class, Object, Variable, Function', 'c' => 'Stack, Heap, Queue, Array', 'd' => 'Compiler, Linker, Interpreter, Virtual Machine', 'correct' => 'A', 'exp' => '4 đặc tính cốt lõi của OOP: Đóng gói, Kế thừa, Đa hình, Trừu tượng.'],
        6  => ['q' => 'Khái niệm "Class" (Lớp) trong OOP được định nghĩa là gì?', 'a' => 'Một khuôn mẫu (blueprint) định nghĩa các thuộc tính và hành vi của đối tượng', 'b' => 'Một vùng nhớ cụ thể trên RAM', 'c' => 'Một biến chứa giá trị số', 'd' => 'Một tập tin chứa hình ảnh', 'correct' => 'A', 'exp' => 'Class là bản thiết kế, Object là thể hiện thực tế của bản thiết kế đó.'],
        7  => ['q' => 'Khái niệm "Object" (Đối tượng) trong OOP là gì?', 'a' => 'Một thể hiện cụ thể (instance) được tạo ra từ Class', 'b' => 'Tên tập tin nguồn', 'c' => 'Từ khóa reserved của ngôn ngữ', 'd' => 'Hình vẽ giao diện', 'correct' => 'A', 'exp' => 'Đối tượng là thể hiện cụ thể mang dữ liệu riêng biệt được sinh ra từ lớp.'],
        8  => ['q' => 'Ghi đè phương thức (Method Overriding) xảy ra khi nào?', 'a' => 'Lớp con định nghĩa lại một phương thức đã có ở lớp cha với cùng tên, cùng tham số', 'b' => 'Viết nhiều hàm cùng tên trong 1 lớp', 'c' => 'Đổi tên biến trong hàm', 'd' => 'Xóa hàm lớp cha đi', 'correct' => 'A', 'exp' => 'Overriding cho phép lớp con cung cấp cách xử lý riêng cho phương thức của lớp cha.'],
        9  => ['q' => 'Ghi đè phương thức (Method Overriding) thể hiện tính đa hình ở thời điểm nào?', 'a' => 'Runtime (Lúc thực thi)', 'b' => 'Compile-time', 'c' => 'Build-time', 'd' => 'Design-time', 'correct' => 'A', 'exp' => 'Overriding là Runtime Polymorphism (được quyết định lúc chương trình chạy dựa trên đối tượng thực tế).'],
        10 => ['q' => 'Từ khóa truy cập `private` giới hạn phạm vi sử dụng của thành phần ở đâu?', 'a' => 'Chỉ bên trong chính Lớp đó', 'b' => 'Trong cùng package', 'c' => 'Ở tất cả các lớp con', 'd' => 'Toàn bộ dự án', 'correct' => 'A', 'exp' => 'private có phạm vi truy cập hẹp nhất, chỉ xem/sửa được trong nội bộ lớp khai báo.'],
        11 => ['q' => 'Từ khóa truy cập `protected` cho phép truy cập ở phạm vi nào?', 'a' => 'Trong cùng package và ở các lớp con (ngay cả khác package)', 'b' => 'Chỉ trong nội bộ lớp', 'c' => 'Công khai toàn ứng dụng', 'd' => 'Chỉ ngoài package', 'correct' => 'A', 'exp' => 'protected mở rộng quyền cho các lớp kế thừa (subclass) ở khác package.'],
        12 => ['q' => 'Nếu không ghi phạm vi truy cập (Default/Package-private trong Java) thì thành phần đó dùng được ở đâu?', 'a' => 'Chỉ các lớp trong CÙNG Package', 'b' => 'Mọi nơi trong project', 'c' => 'Chỉ lớp con khác package', 'd' => 'Chỉ trong nội bộ hàm', 'correct' => 'A', 'exp' => 'Mặc định (no modifier) chỉ cho phép truy cập bởi các lớp nằm cùng package.'],
        13 => ['q' => 'Từ khóa `public` có ý nghĩa gì?', 'a' => 'Có thể truy cập từ bất kỳ đâu trong dự án', 'b' => 'Chỉ truy cập từ lớp con', 'c' => 'Không cho ai truy cập', 'd' => 'Chỉ đọc không cho ghi', 'correct' => 'A', 'exp' => 'public mở rộng phạm vi truy cập tối đa.'],
        14 => ['q' => 'Hàm tạo (Constructor) có đặc điểm nổi bật nào?', 'a' => 'Cùng tên với Lớp, không có kiểu trả về và tự động chạy khi dùng từ khóa `new`', 'b' => 'Trả về kiểu int', 'c' => 'Phải khai báo static', 'd' => 'Không thể truyền tham số', 'correct' => 'A', 'exp' => 'Constructor dùng để khởi tạo trạng thái ban đầu cho đối tượng.'],
        15 => ['q' => 'Một lớp có thể có bao nhiêu Constructor?', 'a' => 'Có thể có nhiều Constructor (nạp chồng constructor)', 'b' => 'Duy nhất 1', 'c' => 'Tối đa 2', 'd' => 'Không thể có constructor', 'correct' => 'A', 'exp' => 'Ta có thể nạp chồng (overload) nhiều constructor với các danh sách tham số khác nhau.'],
        16 => ['q' => 'Tính Kế thừa (Inheritance) mang lại lợi ích lớn nhất là gì?', 'a' => 'Tái sử dụng mã nguồn (Code Reusability)', 'b' => 'Tăng tốc độ truy cập internet', 'c' => 'Tự động sửa lỗi syntax', 'd' => 'Giảm kích thước file hình ảnh', 'correct' => 'A', 'exp' => 'Kế thừa giúp lớp con thừa hưởng code của lớp cha mà không cần viết lại.'],
        17 => ['q' => 'Quan hệ giữa lớp `Car` và lớp `Vehicle` thường là mối quan hệ gì trong OOP?', 'a' => 'Quan hệ Kế thừa (IS-A: Car is a Vehicle)', 'b' => 'Quan hệ Sở hữu (HAS-A)', 'c' => 'Không có quan hệ', 'd' => 'Quan hệ song song', 'correct' => 'A', 'exp' => 'Kế thừa thể hiện mối quan hệ "IS-A" (Xe ô tô LÀ MỘT Phương tiện).'],
        18 => ['q' => 'Quan hệ HAS-A (Composition / Aggregation) thể hiện điều gì?', 'a' => 'Một lớp chứa một thể hiện của lớp khác làm thuộc tính (Ví dụ: Car HAS-A Engine)', 'b' => 'Lớp con kế thừa lớp cha', 'c' => 'Hai hàm trùng tên', 'd' => 'Ép kiểu dữ liệu', 'correct' => 'A', 'exp' => 'HAS-A thể hiện sự kết hợp/sở hữu giữa các đối tượng (Car có một Engine).'],
        19 => ['q' => 'Tính Trừu tượng (Abstraction) tập trung vào điều gì?', 'a' => 'Chỉ hiển thị các tính năng cần thiết và ẩn đi sự phức tạp trong cài đặt', 'b' => 'Viết code thật dài', 'c' => 'Tạo giao diện đẹp', 'd' => 'Xóa hết biến', 'correct' => 'A', 'exp' => 'Trừu tượng hóa giúp người dùng tương tác với đối tượng mà không cần biết phức tạp bên trong.'],
        20 => ['q' => 'Tính Đa hình (Polymorphism) cho phép điều gì?', 'a' => 'Một hành vi/phương thức có thể thực thi theo nhiều cách khác nhau tùy thuộc đối tượng gọi nó', 'b' => 'Tạo nhiều biến trùng tên', 'c' => 'Một lớp kế thừa 100 lớp cha cùng lúc', 'd' => 'Đổi kiểu dữ liệu liên tục', 'correct' => 'A', 'exp' => 'Đa hình: "Một giao diện, nhiều cách triển khai".'],
        21 => ['q' => 'Đa thừa kế (Multiple Inheritance) từ nhiều Lớp cha gây ra vấn đề gì nổi tiếng?', 'a' => 'Vấn đề Kim Cương (Diamond Problem)', 'b' => 'Null Pointer Error', 'c' => 'Stack Overflow', 'd' => 'Out of Memory', 'correct' => 'A', 'exp' => 'Diamond Problem xảy ra khi 2 lớp cha có cùng phương thức khiến lớp con không biết gọi hàm của cha nào.'],
        22 => ['q' => 'Java giải quyết bài toán Đa thừa kế như thế nào?', 'a' => 'Không cho phép đa thừa kế Lớp, nhưng cho phép triển khai nhiều Interface', 'b' => 'Bỏ tính kế thừa', 'c' => 'Cho phép kế thừa tối đa 3 lớp', 'd' => 'Dùng từ khóa super', 'correct' => 'A', 'exp' => 'Java sử dụng Interface để đạt được đa thừa kế hình thức an toàn.'],
        23 => ['q' => 'Từ khóa `this` trong OOP đại diện cho đối tượng nào?', 'a' => 'Đại diện cho chính thể hiện (instance) hiện tại đang thực thi code', 'b' => 'Đại diện cho lớp cha', 'c' => 'Đại diện cho lớp con', 'd' => 'Đại diện cho biến toàn cục', 'correct' => 'A', 'exp' => '`this` trỏ tới chính đối tượng đang gọi phương thức/constructor.'],
        24 => ['q' => 'Nạp chồng phương thức (Overloading) KHÔNG thể chỉ dựa vào sự thay đổi của yếu tố nào?', 'a' => 'Chỉ thay đổi Kiểu trả về (Return type)', 'b' => 'Số lượng tham số', 'c' => 'Kiểu dữ liệu tham số', 'd' => 'Thứ tự các tham số', 'correct' => 'A', 'exp' => 'Hai hàm cùng tên cùng tham số nhưng chỉ khác kiểu trả về sẽ bị LỖI biên dịch.'],
        25 => ['q' => 'Interface có thể khởi tạo đối tượng bằng từ khóa `new` trực tiếp được không?', 'a' => 'Không thể khởi tạo trực tiếp Interface', 'b' => 'Có thể khởi tạo bình thường', 'c' => 'Chỉ khởi tạo được trên hệ điều hành Linux', 'd' => 'Có nếu dùng thêm từ khóa static', 'correct' => 'A', 'exp' => 'Interface và Abstract Class không thể instantiation trực tiếp (trừ khi dùng Anonymous Class).'],
        26 => ['q' => 'Hiện tượng "Upcasting" trong OOP là gì?', 'a' => 'Chuyển đổi tham chiếu đối tượng từ Lớp con lên Lớp cha (Luôn an toàn)', 'b' => 'Chuyển từ Lớp cha xuống Lớp con', 'c' => 'Ép kiểu số nguyên sang số thực', 'd' => 'Xóa bỏ lớp cha', 'correct' => 'A', 'exp' => 'Upcasting ép kiểu ngược về lớp cha, luôn được tự động và an toàn.'],
        27 => ['q' => 'Hiện tượng "Downcasting" trong OOP là gì?', 'a' => 'Chuyển đổi tham chiếu từ Lớp cha xuống Lớp con (Cần ép kiểu rõ ràng và có rủi ro)', 'b' => 'Chuyển từ lớp con lên lớp cha', 'c' => 'Tạo đối tượng mới', 'd' => 'Ghi đè phương thức', 'correct' => 'A', 'exp' => 'Downcasting phải ép kiểu tường minh và dễ ném ClassCastException nếu sai kiểu.'],
        28 => ['q' => 'Trong Java, từ khóa `final` gắn trước tên một Lớp (Class) có ý nghĩa gì?', 'a' => 'Lớp đó không thể bị kế thừa (Không thể tạo lớp con)', 'b' => 'Lớp đó không thể tạo đối tượng', 'c' => 'Lớp đó là lớp trừu tượng', 'd' => 'Lớp đó bị ẩn', 'correct' => 'A', 'exp' => 'Final class (như java.lang.String) bị cấm kế thừa để bảo mật và tối ưu.'],
        29 => ['q' => 'Trong Java, từ khóa `final` gắn trước một Phương thức (Method) có ý nghĩa gì?', 'a' => 'Phương thức đó không thể bị ghi đè (Override) bởi lớp con', 'b' => 'Phương thức không thể gọi', 'c' => 'Phương thức không được có tham số', 'd' => 'Phương thức tự động xóa', 'correct' => 'A', 'exp' => 'Final method bảo vệ logic cốt lõi không cho lớp con sửa đổi.'],
        30 => ['q' => 'Mối quan hệ Aggregation (Gộp) khác Composition (Cấu thành) ở điểm nào?', 'a' => 'Aggregation: Đối tượng con có thể tồn tại độc lập khi đối tượng cha bị xóa; Composition: Đối tượng con chết theo cha', 'b' => 'Aggregation chặt chẽ hơn Composition', 'c' => 'Giống hệt nhau', 'd' => 'Composition không thể chứa dữ liệu', 'correct' => 'A', 'exp' => 'Ví dụ: Phòng học - Học sinh (Aggregation - giải tán phòng học sinh vẫn sống); Nhà - Căn phòng (Composition - phá nhà phòng mất).'],
        31 => ['q' => 'Destructor (Hàm hủy) trong C++ có chức năng gì?', 'a' => 'Dọn dẹp tài nguyên và giải phóng bộ nhớ khi đối tượng bị hủy', 'b' => 'Tạo đối tượng mới', 'c' => 'Kế thừa dữ liệu', 'd' => 'In dữ liệu ra màn hình', 'correct' => 'A', 'exp' => 'C++ sử dụng Destructor (~ClassName) để thu hồi bộ nhớ thủ công.'],
        32 => ['q' => 'Tại sao Java không cần hàm Destructor như C++?', 'a' => 'Vì Java có Garbage Collector tự động thu hồi bộ nhớ rác', 'b' => 'Vì Java không dùng RAM', 'c' => 'Vì Java chỉ chạy được 1 lần', 'd' => 'Vì Java tự động tắt máy', 'correct' => 'A', 'exp' => 'Garbage Collection của Java đảm nhận việc dọn dẹp đối tượng rác.'],
        33 => ['q' => 'Mô hình thiết kế Singleton Pattern đảm bảo điều gì?', 'a' => 'Một Lớp chỉ có duy nhất một thể hiện (instance) trong toàn bộ ứng dụng', 'b' => 'Ứng dụng chạy nhanh gấp 2 lần', 'c' => 'Tạo ra vô số đối tượng', 'd' => 'Không cho phép ghi đè', 'correct' => 'A', 'exp' => 'Singleton đảm bảo 1 instance duy nhất được truy cập toàn cục.'],
        34 => ['q' => 'Mô hình Factory Pattern được dùng để làm gì trong OOP?', 'a' => 'Khởi tạo đối tượng mà không cần chỉ định chính xác Lớp cụ thể trong code gọi', 'b' => 'Lưu trữ cơ sở dữ liệu', 'c' => 'Kiểm thử phần mềm', 'd' => 'Tối ưu hình ảnh', 'correct' => 'A', 'exp' => 'Factory Pattern tạo đối tượng thông qua một interface/hàm chung.'],
        35 => ['q' => 'Coupling (Độ phụ thuộc) trong thiết kế hướng đối tượng nên như thế nào?', 'a' => 'Low Coupling (Phụ thuộc thấp / Lỏng lẻo)', 'b' => 'High Coupling (Phụ thuộc chặt chẽ)', 'c' => 'Max Coupling', 'd' => 'Không cần quan tâm', 'correct' => 'A', 'exp' => 'Thiết kế chuẩn luôn hướng tới Low Coupling để dễ bảo trì và mở rộng.'],
        36 => ['q' => 'Cohesion (Độ gắn kết) trong một Lớp nên như thế nào?', 'a' => 'High Cohesion (Độ gắn kết cao - lớp chỉ làm một nhiệm vụ tập trung)', 'b' => 'Low Cohesion', 'c' => 'Zero Cohesion', 'd' => 'Biến đổi ngẫu nhiên', 'correct' => 'A', 'exp' => 'High Cohesion đảm bảo lớp tập trung giải quyết một trách nhiệm duy nhất.'],
        37 => ['q' => 'Nguyên lý chữ S trong SOLID (Single Responsibility Principle) phát biểu gì?', 'a' => 'Một lớp chỉ nên có một lý do duy nhất để thay đổi (Chỉ làm 1 nhiệm vụ)', 'b' => 'Một lớp làm tất cả mọi việc', 'c' => 'Không được dùng kế thừa', 'd' => 'Tất cả hàm phải private', 'correct' => 'A', 'exp' => 'SRP: Mỗi lớp chỉ nên đảm nhận một trách nhiệm duy nhất.'],
        38 => ['q' => 'Nguyên lý chữ O trong SOLID (Open/Closed Principle) phát biểu gì?', 'a' => 'Mở rộng cho tính năng mới (Open for extension), nhưng Đóng cho việc sửa đổi code cũ (Closed for modification)', 'b' => 'Mở tất cả file code', 'c' => 'Đóng dự án khi có lỗi', 'd' => 'Không cho phép kế thừa', 'correct' => 'A', 'exp' => 'OCP: Thêm tính năng bằng cách viết thêm code/lớp mới chứ không đập code cũ đi sửa.'],
        39 => ['q' => 'Nguyên lý chữ L trong SOLID (Liskov Substitution Principle) có ý nghĩa gì?', 'a' => 'Các đối tượng của lớp con phải có thể thay thế lớp cha mà không làm hỏng tính đúng đắn của chương trình', 'b' => 'Lớp con phải xóa hàm lớp cha', 'c' => 'Lớp cha phải phụ thuộc lớp con', 'd' => 'Không dùng tính đa hình', 'correct' => 'A', 'exp' => 'LSP đảm bảo lớp con tuân thủ đúng hành vi hợp đồng của lớp cha.'],
        40 => ['q' => 'Nguyên lý chữ I trong SOLID (Interface Segregation Principle) khuyến nghị gì?', 'a' => 'Nên chia nhỏ Interface thành nhiều interface chuyên biệt thay vì 1 interface lớn ôm ôm đồm', 'b' => 'Gộp tất cả hàm vào 1 Interface', 'c' => 'Không dùng Interface', 'd' => 'Chỉ tạo 1 hàm duy nhất', 'correct' => 'A', 'exp' => 'ISP: Không ép client phụ thuộc vào các method mà họ không dùng đến.'],
        41 => ['q' => 'Nguyên lý chữ D trong SOLID (Dependency Inversion Principle) nói điều gì?', 'a' => 'Các mô-đun cấp cao không nên phụ thuộc mô-đun cấp thấp; cả hai nên phụ thuộc vào Abstraction', 'b' => 'Code cấp thấp quản lý code cấp cao', 'c' => 'Phụ thuộc trực tiếp vào lớp cụ thể', 'd' => 'Bỏ qua interface', 'correct' => 'A', 'exp' => 'DIP giảm sự phụ thuộc trực tiếp bằng cách code thông qua Interface/Abstraction.'],
        42 => ['q' => 'Phương thức khởi tạo mặc định (Default Constructor) được cung cấp khi nào?', 'a' => 'Khi người dùng KHÔNG viết bất kỳ constructor nào trong lớp', 'b' => 'Luôn luôn có kể cả khi đã viết constructor có tham số', 'c' => 'Chỉ có trong Abstract Class', 'd' => 'Khi khai báo biến static', 'correct' => 'A', 'exp' => 'Nếu bạn tự viết constructor có tham số, compiler sẽ không tự tạo default constructor rỗng nữa.'],
        43 => ['q' => 'Phương thức `toString()` trong OOP/Java có mục đích chính là gì?', 'a' => 'Cung cấp biểu diễn dạng chuỗi văn bản mô tả thông tin đối tượng', 'b' => 'Chuyển chuỗi thành số', 'c' => 'Xóa dữ liệu đối tượng', 'd' => 'So sánh 2 đối tượng', 'correct' => 'A', 'exp' => 'toString() thường được override để in ra thông tin chi tiết của object dạng chuỗi.'],
        44 => ['q' => 'Kỹ thuật "Getter" và "Setter" được dùng để thực thi tính chất nào?', 'a' => 'Đóng gói (Encapsulation)', 'b' => 'Đa hình', 'c' => 'Kế thừa', 'd' => 'Trừu tượng', 'correct' => 'A', 'exp' => 'Getter/Setter giúp kiểm soát việc đọc/ghi các thuộc tính private.'],
        45 => ['q' => 'Biến tĩnh (Static Variable) được chia sẻ như thế nào?', 'a' => 'Dùng chung duy nhất một ô nhớ cho TẤT CẢ các đối tượng được tạo ra từ Lớp đó', 'b' => 'Mỗi đối tượng có 1 bản sao riêng', 'c' => 'Mỗi hàm có 1 bản sao', 'd' => 'Không thể dùng chung', 'correct' => 'A', 'exp' => 'Biến static thuộc về Lớp, tất cả instance đều chia sẻ chung 1 giá trị.'],
        46 => ['q' => 'Lớp Anonynous Inner Class (Lớp vô danh) là gì?', 'a' => 'Lớp không có tên được khai báo và khởi tạo trực tiếp ngay tại vị trí sử dụng', 'b' => 'Lớp bị ẩn bởi phần mềm virus', 'c' => 'Lớp chứa hằng số', 'd' => 'Lớp ở package khác', 'correct' => 'A', 'exp' => 'Anonymous Class dùng để override nhanh phương thức của Interface/Class ngay tại chỗ.'],
        47 => ['q' => 'Khái niệm "Polymorphic Array" (Mảng đa hình) cho phép chứa những gì?', 'a' => 'Mảng kiểu Lớp cha có thể lưu trữ các đối tượng của các Lớp con khác nhau', 'b' => 'Mảng chứa nhiều kiểu dữ liệu không liên quan', 'c' => 'Mảng tự đổi kích thước', 'd' => 'Mảng chỉ chứa được 1 số', 'correct' => 'A', 'exp' => 'Ví dụ: `Animal[] pets = new Animal[]{ new Dog(), new Cat() };`.'],
        48 => ['q' => 'Thuật ngữ "Message Passing" (Truyền thông điệp) trong OOP có nghĩa là gì?', 'a' => 'Việc đối tượng này gọi phương thức của đối tượng khác', 'b' => 'Gửi email giữa các lập trình viên', 'c' => 'Truyền dữ liệu qua mạng internet', 'd' => 'In dữ liệu ra console', 'correct' => 'A', 'exp' => 'Trong OOP, các đối tượng tương tác với nhau bằng cách gửi "thông điệp" (gọi phương thức).'],
        49 => ['q' => 'Hành vi "Copy Constructor" trong một số ngôn ngữ như C++ có tác dụng gì?', 'a' => 'Khởi tạo đối tượng mới bằng cách sao chép dữ liệu từ một đối tượng cùng lớp có sẵn', 'b' => 'Xóa bản sao', 'c' => 'Tạo lớp con', 'd' => 'Đổi tên lớp', 'correct' => 'A', 'exp' => 'Copy Constructor nhân bản đối tượng hiện tại thành đối tượng mới.'],
        50 => ['q' => 'Tại sao nên ưu tiên "Composition over Inheritance" (Dùng cấu thành thay vì kế thừa)?', 'a' => 'Giúp hệ thống linh hoạt hơn, giảm sự gắn kết chặt chẽ và tránh rắc rối khi cây kế thừa quá sâu', 'b' => 'Kế thừa viết tốn ít dòng code hơn', 'c' => 'Kế thừa làm máy tính chạy chậm', 'd' => 'Composition không tốn bộ nhớ', 'correct' => 'A', 'exp' => 'Composition cho phép thay đổi hành vi linh hoạt lúc runtime và tránh phá vỡ tính đóng gói của kế thừa.']
    ]
];

function generateQuestions($bank, $subject_id, $limit) {
    $pool = [];
    if ($subject_id === 'all') {
        foreach ($bank as $cat) {
            $pool = array_merge($pool, array_values($cat));
        }
    } else {
        $pool = array_values($bank[$subject_id] ?? reset($bank));
    }
    
    shuffle($pool);
    $questions = [];
    $poolCount = count($pool);

    for ($i = 0; $i < $limit; $i++) {
        $q = $pool[$i % $poolCount];
        $questions[] = [
            'id'             => $i + 1,
            'question'       => $q['q'] . ($i >= $poolCount ? ' (Ôn tập nâng cao #' . ($i + 1) . ')' : ''),
            'option_a'       => 'A. ' . $q['a'],
            'option_b'       => 'B. ' . $q['b'],
            'option_c'       => 'C. ' . $q['c'],
            'option_d'       => 'D. ' . $q['d'],
            'correct_option' => $q['correct'],
            'explanation'    => $q['exp']
        ];
    }
    return $questions;
}

$_SESSION['gamified_practice'] = [
    'session_id' => 'GAME_' . time(),
    'mode'       => $mode,
    'subject_id' => $subject_id,
    'questions'  => generateQuestions($bank, $subject_id, $limit),
    'start_time' => time()
];

header("Location: do_practice.php");
exit;